### ISSUE TITLE
Ship TwidereX on F-Droid

### ISSUE THREAD

**Issue by ximex** [TwidereProject/TwidereX-Android#10]
Please also ship TwidereX on F-Droid

**Comment by Tlaster** [comment]
WIP: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/7836
Now there's a release for fdroid which is built without firebase, you can download and install it for now

**Comment by tentacleuno** [comment]
@Tlaster I would appreciate any hints as to *where* it is. I'd love to try Twidere X and report my feedback, without having to install the Firebase tracking crap 😛 

Some people like me don't understand any of that Android technical jargon in the MR,
which seems to be important as [I can't actually *find* the app on F-Droid](https://search.f-droid.org/?q=twidere&lang=en).
Is it in an alternative repository, or have you not published it ...?
I'm assuming the inclusion is complete, as the linked MR has been merged.

**Comment by Tlaster** [comment]
@tentacleuno According to [this docs](https://f-droid.org/en/docs/Inclusion_How-To) from F-Droid:

> Provided that your application does not have any build problems, it would takes somewhere **around 24 to 48 hours** from fdroiddata merge until the application to appears in the main repository.  

So the MR just merged and still needs some time, I'll update the readme once the app is on F-Droid.

**Comment by Tlaster** [comment]
Now it's on F-Droid🎉 https://f-droid.org/en/packages/com.twidere.twiderex/

**Comment by tentacleuno** [comment]
Thanks!
