### ISSUE TITLE
[Feature Request] Add lists timelines as column

### ISSUE THREAD

**Issue by f3rcho4r** [TwidereProject/TwidereX-Android#106]
The possibility of adding lists as columns makes Twidere a powerful app and it'd be great to have it in TwidereX.

**Comment by ma-gh** [comment]
+1
Thank you for a pretty smooth Beta!

**Comment by Tlaster** [comment]
It is on the roadmap but not implemented yet, we're planning to support it sometime between 1.5 and 1.6.

**Comment by mbestavros** [comment]
Just wanted to voice my support for this feature as well! Quicker access to lists in general (without needing to open the drawer, which is tedious on Android 10+ gestures) is probably the biggest feature gap for Twidere X for me at the moment. 

Customizable tabs would be fantastic, though a potentially quicker stopgap solution could be a launcher shortcut or widget for a specific list. Not sure what's involved in implementing something like that, though.

**Comment by Tlaster** [comment]
>Just wanted to voice my support for this feature as well! Quicker access to lists in general (without needing to open the drawer, which is tedious on Android 10+ gestures) is probably the biggest feature gap for Twidere X for me at the moment.

Yeah, we're still tweaking the design for it, this is the feature we definitely want it. And as for the drawer, we're investigating options that can be better (like what Google Play does)
