### ISSUE TITLE
Choppy scrolling 

### ISSUE THREAD

**Issue by slaeprop** [TwidereProject/TwidereX-Android#11]
Android: 5.5.1
Twidere X: 1.0.0-alpha06b
Video: https://files.catbox.moe/4zbkkk.mp4

**Comment by mbestavros** [comment]
I ran into this as well. I was able to significantly alleviate the issue by turning off autoplay in Settings -> Display -> Auto Playback, so I'd suggest giving that a try. Scrolling is now pretty smooth for me.

To me, this suggests the app is attempting to start media playback as soon as the viewport scrolls over it, even if there is active movement/scrolling. Being less aggressive about starting media playback might be a possible quick fix -- maybe if the viewport is focused on the video for more than a set threshold?

**Comment by crepusculi** [comment]
I'd like to bump this back up. As of 1.0.6 dev-01, this behavior seems to have resurfaced.

**Comment by ikurek** [comment]
+1, this still seems to be an issue. In my case, turning off the automatic playback feature solved the issue with low frame rate, but the scroll still has a weird feeling, probably due to the "bounce" animation

**Comment by sashaaaaaaaaa** [comment]
disabling Auto Playback doesn't do anything for me, still really choppy. android 12 on lg v50x
