### ISSUE TITLE
[Bug] Weird spacing when setting smaller text size. 

### ISSUE THREAD

**Issue by Sylphystia** [TwidereProject/TwidereX-Android#12]
# Bug Report

## Environment

Network type:

- [ ] Cellular
- [X] Wi-Fi

## Build Variant

- [X] App Store
- [ ] TestFlight

App version: 
1.0.0-alpha06

### Steps to reproduce

When setting text size to smaller than default, additional spacing appears above and below tweet text, which means tweets end up taking up the same amount of space anyway. 

### Actual Behavior

![Screenshot_20201220-200409_Twidere X](https://user-images.githubusercontent.com/7352032/102722104-2896d780-42ff-11eb-88e2-dd5f4ce8ac35.jpg)

###  Expected behavior

No additional spacing.

**Comment by jk234ert** [comment]
Hi @Sylphystia, the spacing looks larger when you use smaller font size setting, but it should be the same as in other font size settings. You could confirm it by comparing 2 screenshots in different font size.
