### ISSUE TITLE
[UI Request] Make the navbar background color match the toolbar 

### ISSUE THREAD

**Issue by Salt505** [TwidereProject/TwidereX-Android#148]
Like many other apps do, can you make the navbar background color in Twidere X match the color of the toolbar? It would look really clean! Thanks :)

Here are some examples:
![Screenshot_20210622-113940](https://user-images.githubusercontent.com/44946401/122910986-b99e4800-d34e-11eb-9832-f7fcacc34e45.jpg)
Twidere X in dark mode
![Screenshot_20210622-113928](https://user-images.githubusercontent.com/44946401/122910989-ba36de80-d34e-11eb-832d-aed6ff88d70a.jpg)
Google Play Store in dark mode

----

![Screenshot_20210622-113913](https://user-images.githubusercontent.com/44946401/122910994-bacf7500-d34e-11eb-998f-8ccc202d04ed.jpg)
Twidere X in light mode 
![Screenshot_20210622-113853](https://user-images.githubusercontent.com/44946401/122910995-bacf7500-d34e-11eb-91de-8dbf92442166.jpg)
Google Play Store in light mode

**Comment by Tlaster** [comment]
If you try version 1.3.0 the navigation bar color is no longer black in light mode, which should look cleaner for now. We're still investigating some options here.
