### ISSUE TITLE
Please support threads

### ISSUE THREAD

**Issue by elchenberg** [TwidereProject/TwidereX-Android#17]
Please support threads.

Threads have become very common on Twitter. So common that Twitter provides a help page: [How to create a thread on Twitter](https://help.twitter.com/en/using-twitter/create-a-thread)

However, when I open the first tweet of a thread in Twidere X (or Twidere) the view is very different from the view on Twitter. Twidere shows all the replies to the thread's first tweet, EXCEPT the next tweet of the thread by the original poster (to be fair, the next tweet might be hidden somewhere in the replies :shrug:). In order to get a thread view in Twidere I have to open the last tweet of a thread, but that is not how threads get shared / retweeted on Twitter.

Example:

Start of a thread: <https://twitter.com/vanteficient/status/1343925279039893504>

How it looks on Twitter (Web):

![image](https://user-images.githubusercontent.com/23496411/103293251-c705f580-49ef-11eb-8be9-cecd69b77341.png)

How it looks in Twidere X:

![image](https://user-images.githubusercontent.com/23496411/103293626-88246f80-49f0-11eb-99cf-93d4e3027503.png)

**Comment by yoshimo** [comment]
This would make threadreaderapp.com and similar services redundant

**Comment by Tsukimoe** [comment]
This needs to be processed for the returned but content and can be added to future features.

**Comment by winterhazelly** [comment]
> This would make threadreaderapp.com and similar services redundant

threadreaderapp is a service that monetises people's content without their consent and many people have it blocked, so respectfully I don't find this a good excuse to avoid implementing core functionality.

**Comment by yoshimo** [comment]
It was my intention to get rid of them and have a good thread support inside Twidere. Don't get that wrong :)

**Comment by p0wl90** [comment]
Yes I just came here to report that Twidere X shows all answers *except* the actual thread responses. This is really the last feature that hinders me from fully switchting to Twidere X :)
