### ISSUE TITLE
Support for twitter lists and others

### ISSUE THREAD

**Issue by elliots2007** [TwidereProject/TwidereX-Android#18]
Support for Twitter list, an inbuilt tweet shortener and notification support.

**Comment by Tsukimoe** [comment]
Twitter list
It seems that the content of the added list can be viewed now, and it can be realized in the future.
Built-in tweet shortener
This feature can be added to the editor, a secondary goal.
Notification support
It seems that a push service needs to be provided in the existing API, which may not be realized.

**Comment by mbestavros** [comment]
I'd like to second Twitter list support. It's how I do most of my browsing. Support for it would probably ensure I could switch over to TwidereX full time.

Ideally, it would be a bottom tab option, just like on the original Twidere -- super easy to access.

**Comment by Tlaster** [comment]
Twitter/Mastodon lists support was done in 1.2.0-beta01, we'll have a stable release after the testing
