### ISSUE TITLE
[Feature Request] User Mention Helper

### ISSUE THREAD

**Issue by crepusculi** [TwidereProject/TwidereX-Android#186]
**Is your feature request related to a problem? Please describe.**
In the main Twitter app, when you type the at symbol (@) followed by some text, the app shows suggested users to mention in the tweet you're composing. In Twidere X, there is no helper/auto-complete for user mentions.

**Describe the solution you'd like**
When typing the "at" symbol (@) on the compose screen followed by text, a helper/dropdown menu to appear with users that match that string as it's typed, possibly sorted/with preference for users I follow or follow me.

**Describe alternatives you've considered**
I could memorize every twitter user's handle, but that seems like a bit much! The only alternative is to switch over to the main Twitter app to get the user's handle/compose the tweet mentioning that user.

**Additional context**
How it currently looks in Twidere X:
![Screenshot_20210713-093035](https://user-images.githubusercontent.com/11526535/125481535-58ff93fb-1182-4fda-92f1-76f310b0bb9a.png)

How it looks in the main app:
![Screenshot_20210713-093102](https://user-images.githubusercontent.com/11526535/125481561-575a3560-81f3-412d-900f-62e2cc346c6e.png)

**Comment by crepusculi** [comment]
If possible, at the same time, do the same thing with hashtags. See the example from the main Twitter app below:

![Screenshot_20210715-161842](https://user-images.githubusercontent.com/11526535/125864998-2fc91848-c1b5-451f-b5de-5197ac1d8a4b.png)

**Comment by Tlaster** [comment]
Here is just a simple implementation without hashtag support, and will improve in future release
