### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by OliverLew** [TwidereProject/TwidereX-Android#20]
# Bug Report

## Environment

Network type:

- [ ] Cellular
- [x] Wi-Fi

## Build Variant

- [ ] Google Play
- [x] FDroid

App version: 
1.0.0-alpha07

### Steps to reproduce

search an exact user name (the `@name`)

### Actual Behavior

the search result is duplicating it self and the result list is full of the same user

###  Expected behavior

there is only one  (if no other username contain this name) item in the result

**Comment by Tlaster** [comment]
This was fixed by bde683456b0d0a36d68329ca3001d9d14f45344c
