### ISSUE TITLE
[Feature Request] Option to show the timeline in chronological order

### ISSUE THREAD

**Issue by Jacksper13** [TwidereProject/TwidereX-Android#204]
Twitter has the option to show content in chronological order or "highlighted for you" or "recommended for you" order (forgot the actual name), and it looks like TwidereX does not have the chronological order option. I am seeing tweets from 5 hours ago higher up than tweets tweeted 30 minutes ago because some algo decided it was more relevant for me, which I always found annoying. 

An option to chronologically order the tweets would be amazing for TwidereX

**Comment by Tlaster** [comment]
As far as I know, this is an API limitation from Twitter, currently, there's no option to do so, but Twidere X does order the timeline in chronological order, if you're using the version that is before 1.4, please try the latest version, it might be a bug #165 which was fixed in 1.4

**Comment by Jacksper13** [comment]
Roger that - thanks!
