### ISSUE TITLE
[BUG] Video squeeze

### ISSUE THREAD

**Issue by ZorinArch** [TwidereProject/TwidereX-Android#220]
**Describe the bug**
Videos is shown squeezed in TwidereX. This also happen with  photos.

**Screenshots**

## Twitter
![twitter-video](https://user-images.githubusercontent.com/62427713/126983678-47de9a5c-612d-41c8-a954-4554d2deed9e.png)

## TwidereX
![twidereX-video](https://user-images.githubusercontent.com/62427713/126983773-ebfeb7e0-fbdb-435c-83be-df5254ffe038.png)

**Smartphone**
 - Device: lenovo A5500
 - OS: Android 7
 - Variant FDroid
 - Version 1.4.0

**Comment by Tlaster** [comment]
Currently, this behavior is by design, just in case that certain image or video is too long to show for a phone, so we limit the max height for the media but still keep the aspect ratio for the media.
