### ISSUE TITLE
[Feature Request] Allow the usage of other API keys, including official Twitter client keys.

### ISSUE THREAD

**Issue by gnusuari0** [TwidereProject/TwidereX-Android#23]
Currently TwidereX only works with TwidereX app keys. It'd nice to be able to use other app keys, as old Twidere does.

**Comment by Tlaster** [comment]
This is in the roadmap but there's no guarantee that the official key or other API keys will work well since Twidere X uses the new v2 Twitter API, which is not compatible with the existing v1 key

**Comment by Tlaster** [comment]
Release 1.0.3 come with custom API key support but require a new v2 API key, there's no guarantee that the existing v1 key and the official key will work well.
