### ISSUE TITLE
Bitwarden doesn't prompt password autofill at twitter login/twidere authentication.

### ISSUE THREAD

**Issue by solonovamax** [TwidereProject/TwidereX-Android#24]
## Issue description.
I'm using bitwarden on mobile, which emulates a screen reader to prompt autofilling of passwords.

There's something you did with the login dialogue so that it doesn't work with bitwarden. This could be considered an issue for bitwarden, but I'm opening it here anyways. (I'll open it on the bitwarden repo later.)

Also, the non-X app worked fine with bitwarden, so idk.

## Reproducing:

- Install bitwarden
- log in to bitwarden.
- enable the autofill service and the autofill accessibility service in bitwarden's settings.
- install twedereX.
- go to the login page for twedereX and tap the login box.

### Expected:
When tapping the login box, it should prompt to autofill from bitwarden (even if you have no passwords associated with twitter/twedere.)

### Actual:
Nothing appears when tapping the box. You must go into bitwarden & copy it manually.

(I wrote this on my phone, so if the formatting is dogshit, then I apologize for that. I'll fix it later.)

**Comment by Kreuger** [comment]
Sometimes I find Bitwarden is finnicky and I have to try it a couple of times. I even sometimes just copy and paste the passwords in when it wont work. I dont think its a problem with TwidereX as Ive had it with other apps.

**Comment by snkfxx** [comment]
I experience the same issue as OP.

**Comment by EliotHertenstein** [comment]
Having the same issue here

**Comment by crepusculi** [comment]
I don't know if I should spin out a separate issue for this, but I'm seeing the same behavior with Enpass as well.
