### ISSUE TITLE
[Feature Request] moving between tags by swiping.

### ISSUE THREAD

**Issue by solonovamax** [TwidereProject/TwidereX-Android#25]
### Describe the feature request
TL;DR: you can't swipe to move between the tabs.

### Describe the solution you'd like
It'd be nice if you could swipe left & right to move between the tabs.

### Describe alternatives you've considered
The alternative is just *not* being able to move between the tabs from a swipe, which is kind of annoying.

Not going to make a long issue for this or anything, because nobody cares.

**Comment by Kreuger** [comment]
Maybe a setting toggle. I dont like apps that do this because I always end up swiping sideways when trying to scroll up/down.

**Comment by Tlaster** [comment]
It's now supported after 1.0.6🎉
We can still make a option that disable this functionality.
