### ISSUE TITLE
[Feature Request] Direct share button when viewing image or video

### ISSUE THREAD

**Issue by scubajeff** [TwidereProject/TwidereX-Android#258]
**Is your feature request related to a problem? Please describe.**
When viewing the image or video, no way to share it to other apps. Have to download it first and then share it from file manager.

**Describe the solution you'd like**
A direct share function when viewing image or video

**Comment by JoeSteven** [comment]
Hi @scubajeff, I'm not sure the version of your TwidereX, We already supported this feature in version 1.4.0: #149
