### ISSUE TITLE
[Feature request] separate tweets and replies tab

### ISSUE THREAD

**Issue by solonovamax** [TwidereProject/TwidereX-Android#26]
It's pretty simple, so I'm not going to make a long issue that nobody wants to read. (This is the last one, I promise.)

Right now if you go on someone's profile you have the "tweets" tab, the "media" tab, and the "likes" tab. If you could split the "tweets" tab into "tweets, qrts, and rts" and "tweets, qrts, rts, and replies", that'd be great. Thanks.

**Comment by Tlaster** [comment]
After 1.1.0 you can now filter profile timeline by replies.
