### ISSUE TITLE
[BUG] Not all URL previews. 

### ISSUE THREAD

**Issue by justinesmithies** [TwidereProject/TwidereX-Android#262]
**Describe the bug**
On the timeline with url previews on not all urls are previewed. Some do preview if you click on the tweet first then go back to your timeline.

**To Reproduce**
1. Go to timeline
2. Look for tweets with a url that isnt previewed
3. Enter into the tweet and it will sometimes preview.
4. Go back to the timeline and it will stay previewed.

**Expected behavior**
With the setting url preview on all links should preview.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Oneplus 5]
 - OS: [e.g. Android 10]
 - Variant [FDroid]
 - Version [e.g. 1.4.0]

**Additional context**

**Comment by ksangwin** [comment]
I've noticed the exact same thing. URLs never preview in the timeline view, but after clicking on a tweet will cause it to preview, then going back to the timeline the preview will persist.

**Comment by gammacray** [comment]
Third for this issue.

**Comment by OliverLew** [comment]
There is preview? I thought that's not a thing in twidere, lol. (If a preview does not look like a normal image or video)

**Comment by Tarek-Hasan** [comment]
Please resolve this issue. It's counterproductive and annoying.
And only thing keeping me from deleting official Twitter app.

**Comment by phillipprado** [comment]
I also am experiencing this bug and would like to request a patch as well.
