### ISSUE TITLE
[BUG]About tweeting

### ISSUE THREAD

**Issue by oksya8and8** [TwidereProject/TwidereX-Android#263]
**Describe the bug**
If you try to delete sentences written in Japanese or Chinese in a tweet, it will not work correctly.

**To Reproduce**
1. Switch keyboards
2. Enter your tweet
3. Press and hold Delete
4. Only one character will be deleted

**Expected behavior**
No different from English.

**Comment by JoeSteven** [comment]
Thanks for reporting, I believe it‘s a bug of Jetpack compose library as I reproduced it with a simplest sample project. I reported this issue to Google:https://issuetracker.google.com/issues/195968614, hope they can fix this soon.

**Comment by HuixingWong** [comment]
This is fixed in latest compose
