### ISSUE TITLE
[Feature Request] Select text in tweet rather than the whole tweet

### ISSUE THREAD

**Issue by scubajeff** [TwidereProject/TwidereX-Android#268]
**Is your feature request related to a problem? Please describe.**
Currently we can only select the whole tweet

**Describe the solution you'd like**
Let user select some text in the tweet rather than the whole tweet, so that the user can share the selected text for searching, looking up in dictionary, wikipedia etc.

To allow other apps add action when user select text in TwidereX, please also add the following to Twidere's manifest:
```
<queries>
 <intent>
   <action android:name="android.intent.action.PROCESS_TEXT" />
   <data android:mimeType="text/plain" />
 </intent>
</queries>
```
Please refer to https://developer.android.com/training/package-visibility/use-cases#custom-text-selection-actions

**Comment by Tlaster** [comment]
While we can make text content selectable, but Compose currently does not support the text selection toolbar.

**Comment by dmint789** [comment]
Please, please enable this feature! If not by default, then at least as a selectable setting. I HATED the official twitter app for not letting me select text, but then thankfully Twidere fixed it. Now Twidere X doesn't have this feature :(

**Comment by Tlaster** [comment]
Done after 1.7.0-beta01.
