### ISSUE TITLE
1.0.0 crashes at startup

### ISSUE THREAD

**Issue by Kreuger** [TwidereProject/TwidereX-Android#27]
Hey I just installed the new 1.0.0 and the app crashes as soon as I try to open it and then I get the message that it keeps closing.

**Comment by Kreuger** [comment]
I uninstalled it, tried again and now it works. For what its worth, the first time I used AppManager to install it. The second time I just used the Android package installer. Not sure if that matters but I thought Id mention it.

**Comment by Tlaster** [comment]
oops my fault, I will push a hotfix and bump to 1.0.1
anyone that having the same issue please uninstall and reinstall to resolve this issue

**Comment by Kreuger** [comment]
Do we need to uninstall again for 1.0.1?

**Comment by Tlaster** [comment]
No, it should be ok

**Comment by Kreuger** [comment]
Thanks, it worked!
