### ISSUE TITLE
[Feature Request] Please support link preview (from Twidere) and "Activities"?

### ISSUE THREAD

**Issue by gthbusrr** [TwidereProject/TwidereX-Android#29]
1. Show link preview (Like how it's implemented in Twidere)
2. This sort of stuff, whatever it's called.
<img width="504" alt="Screenshot 2021-01-17 at 09 13 06" src="https://user-images.githubusercontent.com/77537216/104828428-2a51ad80-5861-11eb-8f7f-1c16af1eab2a.png">

Thank you very much!

**Comment by p0wl90** [comment]
The newest version actually supports "this kind of stuff" when it's a retweet. I fully agree that it should also display an indicator for replies! :)
