### ISSUE TITLE
[Feature Request] Add Load Item Limit Slider

### ISSUE THREAD

**Issue by realmain** [TwidereProject/TwidereX-Android#302]
**Is your feature request related to a problem? Please describe.**
It is annoying to click **Load More** so often because it currently only allows you to load 20 tweets at a time.

**Describe the solution you'd like**
Add a slider like in Twidere (Settings -> Content -> Load item limit) that allows you to load 10-200 items depending on choice.

**Comment by OiCkilL** [comment]
**We will optimise autoloading in the following way.**

When the user first opens the app, the last 40 items will be loaded by default. When the user reaches the 40th item and presses the load more button, auto-load mode will begin. The next 20 items will be loaded automatically, and when the user reaches the next 15 items, the next 20 items will be loaded automatically until the oldest post is viewed.

**Comment by starsoccer** [comment]
I really look forward to the above change. If II can throw in a small suggestion, could all the numbers above be configurable?

For instance loading 50 items, and then on load more button being pressed loading 25 items and then after 20 items load the next 25 etc..

**Comment by OiCkilL** [comment]
> I really look forward to the above change. If II can throw in a small suggestion, could all the numbers above be configurable?
> 
> For instance loading 50 items, and then on load more button being pressed loading 25 items and then after 20 items load the next 25 etc..

We don't want the user to be concerned about that. The aforementioned are just examples, we will test a reasonable parameter and give it to the app.

**Comment by starsoccer** [comment]
Understand, it would just be nice for power users to be able to customize this if they want to. For instance on a slow connection I can imagine wanting to load more items much sooner then on a fast connection only loading when Im a few away.
