### ISSUE TITLE
[BUG] Clicking on the searchbar already with text

### ISSUE THREAD

**Issue by icarlyfanclub** [TwidereProject/TwidereX-Android#304]
**Describe the bug**
When you search something and want to edit the search, clicking on the searchbar again, instead of letting you edit the already made search, the searchbar is empty.

**To Reproduce**
1. Search "test"
2. Click on the searchbar again
3. It is empty

**Expected behavior**
The searchbar should have the text "test" in it, in that way, letting you edit your previous search instead of having to write it again.

**Smartphone (please complete the following information):**
 - Device: Galaxy M20
 - OS: Android 11
 - Variant FDroid
 - Version 1.5.1

**Additional context**
Sorry for the repetitive way that I wrote.

**Comment by HuixingWong** [comment]
closes  #388
