### ISSUE TITLE
[BUG] Letter spacing is too wide

### ISSUE THREAD

**Issue by nevillepark** [TwidereProject/TwidereX-Android#306]
**Describe the bug**
In most of the UI, there is too much space between letters, making text l o o k  l i k e  t h i s. It is hard to read.

**To Reproduce**
View the same tweet in Twidere X and old Twidere; the spacing is noticeably wider in Twidere X. 
Or, compare a hashtag in the Trends list and column title with how it appears in a tweet.

**Expected behavior**
Letter spacing should be consistent throughout the app; in tweets, timelines, profiles, etc., letter spacing should be narrower for greater readability

**Screenshots**

Tweet in Twidere vs. Twidere X
![Tweet in old Twidere](https://user-images.githubusercontent.com/16054979/136695914-164a600a-3a55-4a85-b325-4f0c394a03a5.png)
![Twidere_X](https://user-images.githubusercontent.com/16054979/136696366-be6afc32-aa81-4f2f-b0dd-58d51c3f82cd.png)

Hashtags:
![Screenshot_20211010-083824_Twidere_X](https://user-images.githubusercontent.com/16054979/136696374-eb498aa7-7872-4669-87c3-c25ebe752855.png)
Close-up:
![Screenshot_20211010-083824_Twidere_X_1](https://user-images.githubusercontent.com/16054979/136696383-9101c6d9-918d-4691-bb77-85af934fd6bf.png)
![Screenshot_20211010-083824_Twidere_X_2](https://user-images.githubusercontent.com/16054979/136696417-1ace9767-9d17-4526-8e93-fa51e7fca4c2.png)

**Smartphone (please complete the following information):**
 - Device: Moto G5 Plus
 - OS: Lineage OS 17.1 (Android 10)
 - Variant: Google Play
 - Version: 1.5.1

**Additional context**

**Comment by Tlaster** [comment]
This should be fixed once 1.6.0 is released.
