### ISSUE TITLE
[BUG] App crashes when viewing list members

### ISSUE THREAD

**Issue by dmint789** [TwidereProject/TwidereX-Android#310]
**Describe the bug**
The app crashes

**To Reproduce**
1. Go to the lists section
2. Open a list
3. Click on the 3 dots and click "List members"
4. Scroll all the way down
5. The app should crash

**Expected behavior**
Not crashing the app

**Smartphone (please complete the following information):**
 - Device: Honor View 20
 - OS: 10
 - Variant: F droid
 - Version: 1.5.1

**Additional context**

**Comment by HuixingWong** [comment]
Closes #386
