### ISSUE TITLE
[Feature Request] Don't truncate quoted tweets

### ISSUE THREAD

**Issue by IBBoard** [TwidereProject/TwidereX-Android#320]
**Is your feature request related to a problem? Please describe.**
When viewing a timeline, any sufficiently long quoted tweets are truncated. This means that you've got to interact with the tweet to read all of what was being quoted. This didn't happen in the old Twidere.

**Describe the solution you'd like**
Quoted tweets show full text without truncation.

**Describe alternatives you've considered**
Keep using Twidere!

**Additional context**
![Screenshot_20211023-141931](https://user-images.githubusercontent.com/388582/138558652-2f13c56f-7590-4fa1-8eba-f0b622a871d4.jpg)

First quoted tweet is truncated, the second one (hidden by the button) is short enough not to be truncated.

**Comment by edent** [comment]
I think this is caused by 

https://github.com/TwidereProject/TwidereX-Android/blob/f6ae0e8fdd29d1595171e02045f5fb94a995c9f3/common/src/commonMain/kotlin/com/twidere/twiderex/component/status/TimelineStatusComponent.kt#L718
