### ISSUE TITLE
[Feature Request] Block option

### ISSUE THREAD

**Issue by mistertoze** [TwidereProject/TwidereX-Android#324]
Please add a "Block account" button to the "More Option" (•••).

I understand that the profile view is still unfinished in comparison to all the options from the previous Twidere, but this additional Block button would be very appreciated.

Thank you!

**Comment by CoelacanthusHex** [comment]
The environment of Twitter is mixed, and it is very important to be able to block unfavorable/bad accounts at this time.

**Comment by Tlaster** [comment]
Block Twitter user is now supported once 1.6.0 is released
