### ISSUE TITLE
[BUG] Twitter API version error messsage when viewing/selecting tweets

### ISSUE THREAD

**Issue by Feakster** [TwidereProject/TwidereX-Android#329]
**Describe the bug**
I receive an API error message when trying to view comments/replies to tweets selecting them.

**To Reproduce**
1. Open app
2. Select a tweet

**Expected behavior**
When trying to view the replies to tweets I see the following error:

"""
When authenticating requests to the Twitter API v2 endpoints, you must use keys & tokens from a Twitter developer App that is attached to a Project. You can create a project via the developer portal.
"""

**Screenshots**
Will upload later. Don't think my GitHub client app can do this.

**Smartphone (please complete the following information):**
 Pixel 5

**Comment by cnovel** [comment]
Here's a screenshot of the error
![Screenshot_20211109-074021](https://user-images.githubusercontent.com/5690282/140874875-c9981386-db87-4618-83ba-20f11ace7f3f.png)

Happens on my Pixel 4a

**Comment by Feakster** [comment]
Appears to be fine now.
