### ISSUE TITLE
[Bug]  Overhead animation per each touch

### ISSUE THREAD

**Issue by Symbian9** [TwidereProject/TwidereX-Android#33]
# Bug Report

## Environment

Network type:

- [x] Cellular
- [x] Wi-Fi

## Build Variant

- [ ] Google Play
- [x] FDroid

App version: `1.0.1`

## Bug Info

App UI/UX has too much animation per each touch in browsing/stream navigation (like water drops each time touch finger to display, scroll, any event at all)

### Steps to reproduce

Just open app and start browsing

### Actual Behavior

Too much "water drop" GLSL animations acted on each touch action in during browsing.

###  Expected behavior

Add option *"Disable touch animations"*.

**Comment by Tlaster** [comment]
It depends on the Jetpack Compose since it's the default behavior of Jetpack Compose, and it might change in the future.
