### ISSUE TITLE
[Feature Request] Use Material Components as the parent of the base theme, instead of the platform theme

### ISSUE THREAD

**Issue by proletarius101** [TwidereProject/TwidereX-Android#34]
Currently TwidereX uses `android:Theme.DeviceDefault.NoActionBar` [as the parent of the base theme](https://github.com/TwidereProject/TwidereX-Android/blob/faca10462e99be13ab8fc6740c66ff9ab2d0a9ea/app/src/main/res/values/themes.xml#L2), which varies in different platforms, and could even give you Holo theme (on Android 5.0).
Instead, the Google recommended base theme (and is also a best practice) is `Theme.MaterialComponents.DayNight`, [which also supports jetpack compose](https://github.com/material-components/material-components-android-compose-theme-adapter). This will give us good baseline experience for free, and even [a better implementation of the Dark Theme](https://material.io/develop/android/theming/dark).

**Comment by Tlaster** [comment]
I don't think it is still needed in Compose world since Jetpack Compose draws itself like what flutter does. And since the entire app is written in Compose, all theme is defined in Compose, not the traditional XML, `android:Theme.DeviceDefault.NoActionBar` should be enough.

**Comment by proletarius101** [comment]
You're right. After some research, using `androidx.compose.material:material` is enough
