### ISSUE TITLE
[Feature Request] Share button for Tweet

### ISSUE THREAD

**Issue by halmartin** [TwidereProject/TwidereX-Android#344]
I am running Twidere X 1.5.1 from F-Droid.

**Is your feature request related to a problem? Please describe.**
The old version of the Twidere app allowed a user to share the whole Tweet (text + link to tweet). Twidere X lacks this functionality and only allows the user to share the URL to the tweet:
![photo4974443148591868373](https://user-images.githubusercontent.com/1230969/143609572-51fe7401-595d-4024-93a7-8a00d8866301.jpg)

**Describe the solution you'd like**
Twidere X should implement a share feature similar to Twidere, where the contents of the tweet including a link to the tweet can be shared through a single action:
![photo4974443148591868372](https://user-images.githubusercontent.com/1230969/143609343-359c3c08-0b6d-42fc-92aa-d1e977b4da8a.jpg)

Result:
> Testing kernels and device trees, looking pretty good!
> 
> (The Intel iMac is showing the Mac Mini screen) https://t.co/Sd0hxlPGfZ
> 
> https://twitter.com/marcan42/status/1464104488822665219

The "Share Media" feature of Twidere X only shares the media file, not the Tweet text or link of the Tweet. This is a regression from the functionality offered by Twidere:
![Screenshot of Telegram Web](https://user-images.githubusercontent.com/1230969/143609891-3347756e-cb04-4dbe-997e-9f4a4e22cf8b.png)

**Describe alternatives you've considered**
Copying the Tweet text to the clipboard and then sharing the link + pasting the Tweet text is very inefficient compared to the previous share feature in Twidere.

**Additional context**
N/A

**Comment by besendorf** [comment]
I would like to have this feature. But please make this optional. With Twidere it was not optional and looked awful if you shared a tweet in a messenger that implemented URL preview as you saw everything doubled.

**Comment by halmartin** [comment]
> With Twidere it was not optional and looked awful if you shared a tweet in a messenger that implemented URL preview as you saw everything doubled.

The original Twidere allowed you to share a Tweet or share the link to a Tweet. The new Twidere X only allows sharing a link.

I personally prefer the original behaviour of the tweet contents + link.
