### ISSUE TITLE
[Bug] No spaces between followers and number

### ISSUE THREAD

**Issue by edent** [TwidereProject/TwidereX-Android#35]
# Bug Report

## Environment

Network type:

- [X] Cellular
- [X] Wi-Fi

## Build Variant

- [X] Google Play
- [ ] FDroid

App version: 1.0.3

### Steps to reproduce

* Tap on user avatar
* Tap on Following or Followers

### Actual Behavior

Text looks like "Followers123"

![Screenshot of app](https://user-images.githubusercontent.com/837136/106152119-fb96d980-6174-11eb-90ab-6e0dbdf10552.jpg)

###  Expected behavior

Should be "Followers 123" with a space.

And, possibly, other user data.

**Comment by Kreuger** [comment]
Might be worth also separating the name and user's handle as well.

**Comment by Tlaster** [comment]
Yeah we're still tweaking the design for this scene
