### ISSUE TITLE
Feature request: Read from bottom

### ISSUE THREAD

**Issue by nikclayton** [TwidereProject/TwidereX-Android#37]
Twidere has a config option, "Read from bottom" where the read position is retained after refreshing.

As far as I can tell, Twidere-X doesn't currently support this. Refreshing always takes you to the most recent tweet.

Not sure if this is intentional, or on-the-roadmap-but-not-implemented-yet. Hence this feature request.

**Comment by Tlaster** [comment]
It is on-the-roadmap-but-not-implemented-yet, thanks for the feature request!

**Comment by snkfxx** [comment]
Looking forward to seeing this.

Relatedly, would you consider adding the option to reverse the sort order of tweets (i.e. have newest tweets at the bottom)?

**Comment by Pitoucol** [comment]
Hello
You have closed this request, which means for me that it's implemented. 
But with latest version 1.5.0, I can't read from bottom. Load more always send me to the top of my tl.
