### ISSUE TITLE
[Feature Request] Show who liked my content in notifications/mentions.

### ISSUE THREAD

**Issue by Arjab** [TwidereProject/TwidereX-Android#390]
There is not option to view who liked my content. Twitter usually show not only mentions, but also who liked ones tweets and comments in a bundled notification section. Twidere X is only showing the mentions.

I'd like to see a section which bundles notifications like Twitter natively does, showing mentions and who liked my content.

**Comment by OiCkilL** [comment]
Hi, currently the official Twitter API does not support these features.

**Comment by Arjab** [comment]
Thanks, I just found this issue [#941](https://github.com/TwidereProject/Twidere-Android/issues/941) which covers the same issue.
