### ISSUE TITLE
[BUG] Error while deserializing comment response

### ISSUE THREAD

**Issue by TonnyL** [TwidereProject/TwidereX-Android#396]
**Describe the bug**

**To Reproduce**
Check the tweet below.

**Expected behavior**

**Screenshots**
![](https://user-images.githubusercontent.com/13329148/147855361-a723aa49-12c7-48f3-9cc7-c2b1623f4032.jpg)

**Smartphone (please complete the following information):**
 - Device: OnePlus 8T
 - OS: Android 11
 - Variant Google Play
 - Version 1.5.1

**Additional context**

**Comment by qdsfdhvh** [comment]
This is a bug in kotlinx.serialization 1.2.2 [#1600](https://github.com/Kotlin/kotlinx.serialization/issues/1600), new version has been fixed.
