### ISSUE TITLE
[BUG] can't add second account

### ISSUE THREAD

**Issue by h-2** [TwidereProject/TwidereX-Android#414]
**Describe the bug**
I want to add a second twitter account. App-Verification in the browser works, but when I return to the App, I am just back on the start tab of the first account and no second account is added.

**To Reproduce**
1. Go to Settings->Accounts
2. Click on '+'
3. Click Add Twitter
4. It opens Twitter's API verification
5. I successfully log-in and click "authorize app"
6. I am returned to TwidereX, but there is no second account
7. If I repeat the process, I can see on on the Twitter-API page that the second account I want to add is correctly logged in at the top-right. If I click  "authorize app" again, it still does not work.

**Expected behavior**
It should work.

**Screenshots**

--

**Smartphone (please complete the following information):**
 - Device: Redmi K20 Pro
 - OS: MIUI Global 12.5.1 / Android 11
 - Variant: F-Droid
 - Version: 1.5.1

**Additional context**
I have tried adding a Mastodon-account, it also doesn't work (same problem).

**Comment by apacelus** [comment]
Can still reproduce on 1.6.0-dev03

**Comment by h-2** [comment]
Not on Twitter anymore, but thanks for fixing!
