### ISSUE TITLE
[Feature Request] Tabs for specific lists

### ISSUE THREAD

**Issue by h-2** [TwidereProject/TwidereX-Android#415]
**Is your feature request related to a problem? Please describe.**

I use lists instead of follow. On the desktop, I use TweetDeck and it works fine. On my phone I use Twidere and get create tabs for each list. In TwidereX, I need to more clicks to get there.

**Describe the solution you'd like**

I would like to be able to create regular tabs from specific lists, instead of having one tab for all lists.

**Comment by f3rcho4r** [comment]
Already requestes in #295
