### ISSUE TITLE
[Bug] Keyboard isn't displayed 

### ISSUE THREAD

**Issue by sh0nuff** [TwidereProject/TwidereX-Android#42]
Android 11 Pixel 3 XL SwiftKey

Keyboard doesn't appear after app has been backgrounded for some length of time. Can be solved by force closing and reopening app. 

Sometimes the keyboard doesn't show up at all in any of the input areas, other times tapping on a text box causes the keyboard to slide up and then immediately slide back down (very rapid animation) 

Will try and test with other keyboards to see if it's SwiftKey only

**Comment by p0wl90** [comment]
Can confirm this with FlorisBoard (a great new FOSS Keyboard)

**Comment by crepusculi** [comment]
Ditto on the Pixel 3, Android 11, with GBoard.

**Comment by sh0nuff** [comment]
Update : was able to clip a short screengrab of the issue https://photos.app.goo.gl/ovDVzVnoNP7rANqG9

**Comment by Tlaster** [comment]
Close as cannot reproduce, reopen if you got the same issue after 1.7.0
