### ISSUE TITLE
[Feature request] SOCKS5 proxy support

### ISSUE THREAD

**Issue by GEkuL** [TwidereProject/TwidereX-Android#442]
Hi there,

Thanks for the proxy support! That's a great thing for some countries.

Could you add the support for socks proxies? Now it only supports http, which can't be used for connection to the localhost 1080 port of socks proxy.

Will be grateful for the feature. It's the only one needed for use of the Twidere X

**Comment by GEkuL** [comment]
The [issue have been already risen](https://github.com/TwidereProject/TwidereX-Android/issues/160) and seems to be resolved, yet the proxing is still no working. Nor in Twidere nor in Twidere X

Could you fix this small trouble?

**Comment by qdsfdhvh** [comment]
Already done, awaiting merge.

**Comment by GEkuL** [comment]
@qdsfdhvh 
Eagerly awaiting for the new update then :)


Should I close the issue now or wait till the new app version arrives?
