### ISSUE TITLE
[BUG] List view trim tweets

### ISSUE THREAD

**Issue by oriold** [TwidereProject/TwidereX-Android#447]
**Describe the bug**
The tweets in the main timeline show OK, but when you go to a list, they are trim to 140, you need to click on them to expand them.

**To Reproduce**
1. Go to lists
2. Long tweets are trim

**Expected behavior**
We should see the tweets in full or the maximum length should be configurable. At least behaviour should match main timeline. 

**Smartphone (please complete the following information):**
 - Device: [FP14]
 - OS: [Android 11]
 - Variant [FDroid]
 - Version [1.5.1]

**Comment by edent** [comment]
This is caused, I think, by:

https://github.com/TwidereProject/TwidereX-Android/blob/f6ae0e8fdd29d1595171e02045f5fb94a995c9f3/services/src/main/java/com/twidere/services/twitter/api/TimelineResources.kt#L76

It needs this added to the function:

```
@Query("tweet_mode") tweet_mode: String = "extended",
```
