### ISSUE TITLE
[Bug] Profile Pic not loading on tap 

### ISSUE THREAD

**Issue by sh0nuff** [TwidereProject/TwidereX-Android#45]
Opening any user profile, tapping the image causes the profile to flicker but nothing loads. Multiple requests create multiple steps to return back to feed (ie, must tap or swipe back for each time the pic was tapped)

Pixel 3xl Android 11

**Comment by Tedko** [comment]
@Tlaster

**Comment by sh0nuff** [comment]
@Tlaster   FYI this issue still manifests for me , see video capture from my phone [here ](https://photos.app.goo.gl/2CXTsnywbzoWQAAq8) (pls delete this link once you've confirmed) - I couldn't find an updated version of the app in FDroid if it has been fixed

**Comment by Tlaster** [comment]
The fix will be included in the 1.0.6 which will release next week
