### ISSUE TITLE
[BUG] Scrolling isn't Smooth

### ISSUE THREAD

**Issue by alphanerdgen** [TwidereProject/TwidereX-Android#499]
Poor UX thanks to the choppy scrolling in the latest version.

 - OS: Android 12
 - Variant: FDroid
 - Version: 1.6.0

**Comment by YouSummoner** [comment]
Yepp, I've been irritated by extremely jitterish scrolling experience too, it's even worse than the official Twitter app
I'm on Android 12.1. Device Realme XT.

**Comment by mnisius** [comment]
Yes the app is basically not usable. Something is very wrong. The ui kind of wobbles back and forth all over the place...
I have the same behavoir on my poco f1 and on my samsung tab s7 plus. 

Does no one uses this app? I mean this bug exists since the the last release so it's quite old....

**Comment by cunlem** [comment]
Yeah 1.6.0 seems completely broken

**Comment by AndrewPochapsky** [comment]
I thought I was going crazy when I opened the app lol, glad to see this is an issue noticed by others too.
