### ISSUE TITLE
Translation help?

### ISSUE THREAD

**Issue by ApoRes1337** [TwidereProject/TwidereX-Android#5]
Hey,
can we help you with translation of this app? 

Greetz from Germany

**Comment by Tlaster** [comment]
Yes! You can go to https://crowdin.com/project/twidere-x to help us translate the app for both Android and iOS version

**Comment by ApoRes1337** [comment]
> 
> 
> Yes! You can go to https://crowdin.com/project/twidere-x to help us translate the app for both Android and iOS version

Translation for German Language completed. 
Greetz
