### ISSUE TITLE
[Feature Request] Sort Replies

### ISSUE THREAD

**Issue by EliotHertenstein** [TwidereProject/TwidereX-Android#51]
I'm absolutely loving this app, however one thing I'm missing from flamingo is the ability to sort replies by top, instead of most recent. Other then that, love the app!

**Comment by binarious** [comment]
@Tlaster This is closed, but I don't see the option to sort replies in threads by top. I only see the most recent ones. What am I missing? (v1.5.1)

**Comment by Tlaster** [comment]
> @Tlaster This is closed, but I don't see the option to sort replies in threads by top. I only see the most recent ones. What am I missing? (v1.5.1)

It's relatively hard to fetch correct thread order like the Twitter web with the Twitter API, so we provide a nitter option, which can provide a more reliable result for the replies, but still not as good as the official Twitter web, it's a workaround but better than nothing. We're still investigating how to display the replies and the thread that can provide a better user experience.

**Comment by binarious** [comment]
Ah I see. That seems to work good enough for me. Thank you.
