### ISSUE TITLE
[BUG] Notification content is unreadable

### ISSUE THREAD

**Issue by shbhmnk** [TwidereProject/TwidereX-Android#510]
**Describe the bug**
The notification received on TwidereX contains html code and is unreadable.

**To Reproduce**
1. Minimize the app and go to home screen
2. Receive a notification

**Expected behavior**
Notification content should be readable

**Screenshots**
![Screenshot_20221108-041902895 (1).jpg](https://user-images.githubusercontent.com/7382921/200432501-99cb3be0-e370-4f16-a3e7-422cfbed16e1.jpg)

**Smartphone (please complete the following information):**
 - Device: Asus ROG 5s
 - OS: Android 12
 - Variant: FDroid
 - Version: 1.6.0

**Additional context**

**Comment by JoeSteven** [comment]
Fixed but haven't release yet, see: #449
