### ISSUE TITLE
[Bug] The cursor is not set

### ISSUE THREAD

**Issue by toas-koas** [TwidereProject/TwidereX-Android#54]
# Bug Report

## Environment

Network type:

- [ x] Cellular
- [x ] Wi-Fi

## Build Variant

- [ ] Google Play
- [x ] FDroid

App version: 

## Bug Info

I cannot reset the cursor, only mark words. New lines are also not set by pressing the enter key.

**Comment by sh0nuff** [comment]
I also have this same behavior with the current build (1.1.0) - it's not so much that I can't move the cursor, I can, but it's invisible; there's no flashing cursor to communicate where it is in the line of content. I can also confirm that hitting enter doesn't add carriage returns

**Comment by foldfree** [comment]
The cursor is black on black when using dark theme, it is therefore not visible.
