### ISSUE TITLE
[BUG] Can't add multiple twitter accounts

### ISSUE THREAD

**Issue by Sheepyhead** [TwidereProject/TwidereX-Android#540]
**Describe the bug**
I added my main account without issues, but when attempting to add my two side accounts, it goes to twitter's authenticate page, I authenticate, then it returns to the "Hello! Sign in to get started" page in twidere x without having added any accounts to the app.

**To Reproduce**Add any other context about the problem here.
1. Go to 'Sign in'
2. Attempt to sign in with alternate account

**Expected behavior**
I expected to be able to handle multiple accounts like Twidere was capable of

**Smartphone (please complete the following information):**
 - Device: Fairphone 4
 - OS: Android 11
 - Variant Google Play
 - Version 1.6.0

**Additional context**
I tried with two different accounts, neither worked.

**Comment by zigaturk** [comment]
Same here. First account ok, regardless which. Second a problem.

**Comment by griffi-gh** [comment]
can't add any accounts at all

**Comment by Sheepyhead** [comment]
> can't add any accounts at all

I believe twitter now disallows custom clients from using their API at all, so I suspect this project is doomed
