### ISSUE TITLE
[BUG] App data doesn't update after pulldown to refresh

### ISSUE THREAD

**Issue by bushrang3r** [TwidereProject/TwidereX-Android#543]
**Describe the bug**
For the last couple of days, when I create a new tweet with Twidere X, the app doesn't display my tweets. When I log into twitter on desktop, they are visible. Also, it doesn't show any tweets from accounts I follow.
**The older version (Twidere) has also stopped updating.**

**To Reproduce**
1. Create a tweet and tap the send button.
2. View and refresh twitter feed. There is nothing there.

**Expected behavior**
Feed should update and show my new tweet and any other new tweets from accounts I follow. 

**Smartphone (please complete the following information):**
 - Device: OnePlus 7T
 - OS: Android 13 (LineageOS)
 - Variant: FDroid
 - Version: e.g. 1.6.0

**Additional context**
The app did work for my first 3 tweets, but now it doesn't update anymore.

**Comment by bushrang3r** [comment]
Twidere X has started to update again, however, Twidere is still not updating.

**Comment by bushrang3r** [comment]
Twidere X has **stopped** updating again.

**Comment by bushrang3r** [comment]
Twidere X is updating successfully again. It seems that it may not be an issue with the app itself. Could it be an issue with the API, or changes on Twitter's end?

**Comment by Tlaster** [comment]
Seems like you hit the rate limit for home timeline, currently Twitter rate limit for home timeline is 15 requests / 15-min window. For more detail: [Twitter API Document](https://developer.twitter.com/en/docs/twitter-api/v1/tweets/timelines/api-reference/get-statuses-home_timeline)

**Comment by bushrang3r** [comment]
Got it! Thanks!
So, if you go over the limit, the app stops updating for 1-2 days? Wow, that's quite a penalty.

**Comment by Tlaster** [comment]
It should keep update after 15 minutes. If you found out that it stops updating for days, it might be another issue.

**Comment by bushrang3r** [comment]
Sometimes it stops for a day.
I've tried clearing the app cache, and even uninstalling/re-installing the app but it doesn't fix the issue. I just have to wait. I'll be careful from now on about how often I refresh the timeline 👍

**Comment by Tlaster** [comment]
Seems like still a rate limit, but for the application API Key, we will switch to V2 home timeline API in version 1.8 and it should resolve the issue.

**Comment by bushrang3r** [comment]
Understood! Thank you 😉
