### ISSUE TITLE
[Bug] Enter / Return key operates as delete key

### ISSUE THREAD

**Issue by sh0nuff** [TwidereProject/TwidereX-Android#55]
Android 11 Pixel 3 stable (non beta Play version) 

Tapping the enter / return key doesn't add line breaks / carriage returns, instead just operates as delete key. 

See screengrab, I recorded my touches so you can see that both enter and delete perform the same task 

https://photos.app.goo.gl/Vs6SL8rLUcn8Ssvp6

**Comment by Tlaster** [comment]
Thanks! Could you please try the beta version from google play? Does beta version have the same issue?

**Comment by sh0nuff** [comment]
> Thanks! Could you please try the beta version from google play? Does beta version have the same issue?

Funny enough, when I was checking if I had the Fdroid or Play version when logging the issue, I saw that there is a beta build and signed up to check myself. Seems it's still processing the request to join, so I'll update once I am accepted and get the new build pushed

**Comment by HuixingWong** [comment]
> Android 11 Pixel 3 stable (non beta Play version)
> 
> Tapping the enter / return key doesn't add line breaks / carriage returns, instead just operates as delete key.
> 
> See screengrab, I recorded my touches so you can see that both enter and delete perform the same task
> 
> https://photos.app.goo.gl/Vs6SL8rLUcn8Ssvp6

Hello, which keyboard software do you use?

**Comment by sh0nuff** [comment]
I use Swiftkey - Now, I am not sure since it's been a bit since I logged
that issue, but I believe that I tried other keyboards as well, but I can't
be confident on this

[image: photo]
*Jon Moore*

613.276.0077

***@***.***
<http://www.linkedin.com/in/jon-moore-1263589/>
<http://about.me/jonathanmoore> *About me <http://about.me/jonathanmoore>*
<http://bookme.theasset.ca/lite/hangouts> *Click here to hang out!
<https://bookme.theasset.ca/lite/hangouts>*

**Comment by Tlaster** [comment]
Cannot reproduce any more, reopen if someone got the same issue.
