### ISSUE TITLE
[BUG] app is laggy

### ISSUE THREAD

**Issue by Araly** [TwidereProject/TwidereX-Android#562]
**Describe the bug**
the app is laggy, it stutters when it scrolls, it's difficult to predict when scrolling is going to stop, and would probably give me a headache if i used it too much

**To Reproduce**
1. install app
2. use the app
3. scroll by flicking the screen
4. observe that it stops for a short time and then continues scrolling, a lot of times through the scrolling, it stutters.
5. scroll by dragging the finger on the screen without letting go
6. observe that the screen follows the finger, but then stops for a short time like in step 4

everytime it stops it's for a very short time, it's like a stutter, like frame drops in a game or stream.

**Expected behavior**
using the app and scrolling around should be smooth and continuous, like it is in old Twidere

**Smartphone (please complete the following information):**
 - Device: oneplus nord
 - OS: android 12
 - Variant google play (tried to install on fdroid but can't find the app, is it gone ?)
 - Version: 1.6.0

**Additional context**
tried to find a similar issue but couldn't so i wrote this one, hope it's not a duplicate, as it seems like a very obvious issue

**Comment by HuixingWong** [comment]
Try the 1.7.0-beta01 u will find this issue fixed
