### ISSUE TITLE
[BUG] Starting Twitter login process retuns 401 errors

### ISSUE THREAD

**Issue by yakky** [TwidereProject/TwidereX-Android#564]
**Describe the bug**
On a freshly installed instance, the Twitter login process returns 401 errors

**To Reproduce**
1. Start application after data wipe
2. Click on 'Sign in with Twitter'
3. Http 401 toast message is shown

**Expected behavior**
Twitter login process starts

**Screenshots**
![Screenshot_2023-01-22-06-42-26-19_d08dd8d3653238fab8e3ef968e5ccbf8.jpg](https://user-images.githubusercontent.com/714711/213902391-fb5d409d-87a4-4f54-866d-33f83ff15553.jpg)

**Smartphone (please complete the following information):**
 - Device: Oneplus 9
 - OS: Android 13
 - Variant FDroid
 - Version 1.6.0

**Additional context**

My best guess is that they revoked twidere API keys

**Comment by Tlaster** [comment]
Twidere X is also being suspend by Twitter, we will find another way to resolve it.

**Comment by yakky** [comment]
I'm so sorry for the obnoxious behavior of Twitter. Sending all the support for all your work

**Comment by somehuman60** [comment]
I'm getting the same error today. Yesterday worked fine.

**Comment by fauust** [comment]
Same here, good luck.

**Comment by TPAXcc** [comment]
> I'm getting the same error today. Yesterday worked fine.

twitter developer agreement is update right now. Fuk u musk

**Comment by Tlaster** [comment]
👀

**Comment by Sohra** [comment]
It's still not working for me, what's changed @Tlaster?

**Comment by BeauBastion** [comment]
@Sohra, still not working for me as well. @Tlaster may have closed it because it's unfix-able with an update to Twitter based on what @TPAXcc said...

**Comment by jonaskor** [comment]
I installed the app today but also get this error. Is there a fix yet? The app is unusable, if I can't log in...

**Comment by BeauBastion** [comment]
@jonaskor I'm not even sure there will be a fix. The Twitter API is no longer free and I've heard it's stupid expensive. I can't find any updates on the status of TwidereX specifically... I currently use Revanced Manager and an older Twitter APK to remove ads and the like. Hope this helps
