### ISSUE TITLE
[Feature Request] It's dead Jim. Can it be a reader like Fritter?

### ISSUE THREAD

**Issue by fabioromeo** [TwidereProject/TwidereX-Android#566]
So the APIs were revoked and looks like twitter is no more. Can Twidere X be a reader like Fritter, saving liked tweets locally and allowing crossposting with Mastodon? One thing that could be cool is the possibility to see those tweets between the toots, since many accounts doesn't live on the fediverse unfortunately.

**Comment by enaix** [comment]
Theoretically, it is possible to use Twidere X as an anonymous Twitter reader through Nitter proxy right now (may need some tweaks in code)

**Comment by Tlaster** [comment]
It's not dead yet👀, and we still plan to support fediverse platforms like Mastodon or Misskey in the future.
