### ISSUE TITLE
[BUG]1.7.0-beta1 Can't sing-in right now

### ISSUE THREAD

**Issue by TPAXcc** [TwidereProject/TwidereX-Android#567]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel 5]
 - OS: [e.g. Android 11]
 - Variant [e.g. Google Play, FDroid]
 - Version [e.g. 1.2.0]

**Additional context**

**Comment by TPAXcc** [comment]
https://drive.google.com/file/d/1mefU_cxOlB90AO-rGXhsrIrH9neGhM5f/view?usp=drivesdk Demo Video

**Comment by Tlaster** [comment]
See #564 , Twitter currently suspend Twidere X API Key.
