### ISSUE TITLE
[BUG] Unauthorized?????

### ISSUE THREAD

**Issue by bushrang3r** [TwidereProject/TwidereX-Android#568]
**Describe the bug**
Started the app as usual and it seems I'm not logged in anymore. Why did it change?
(Could not authenticate you)
I tap on login, but the same page just reloads over and over again.

**Smartphone (please complete the following information):**
 - Device: OnePlus 7T
 - OS: Android 13 (Lineage OS)
 - Variant: Fdroid
 - Version: 1.6.0

**Comment by Tlaster** [comment]
See #564 , Twitter currently suspend Twidere X API Key.
