### ISSUE TITLE
[BUG] Unparseable date

### ISSUE THREAD

**Issue by ha-ku** [TwidereProject/TwidereX-Android#571]
**Describe the bug**
Clicking into some tweets on the timeline leads to an "Unparseable date" error displayed in the comment area, while clicking on some other tweets doesn't.
For example, I encountered the error when clicking into this one: https://twitter.com/Diesel2b/status/1619931521300967424

**To Reproduce**
1. Go to Timeline tab
2. Click into a tweet.
3. See error

**Expected behavior**
Comments are shown.

**Screenshots**
![Screenshot_2023-01-31-00-38-41-373_com twidere twiderex-edit](https://user-images.githubusercontent.com/18721230/215539148-4728c292-4c3c-4242-8229-bc5b239f7939.jpg)

**Smartphone (please complete the following information):**
 - Device: Xiaomi MIX 4
 - OS: Android 13
 - Variant: Google Play
 - Version: 1.7.0-beta02

**Comment by yoshimo** [comment]
Usually this is connected to certain nitter instances, do you use any?

**Comment by ha-ku** [comment]
> Usually this is connected to certain nitter instances, do you use any?

I'm using a nitter instance held privately by myself. I have tried to rebuild the binary file from the latest code in the nitter repository just now. The error still exists after that.

**Comment by cunnyarc** [comment]
I get the same error using `nitter.net`
