### ISSUE TITLE
Keyboard lag

### ISSUE THREAD

**Issue by Tazgraz19** [TwidereProject/TwidereX-Android#577]
Serious keyboard lag in latest beta. Almost like the code is resetting the keyboard with each stroke/character.

**Comment by wakira** [comment]
Same here. This makes TwidereX completely unusable for CJK input method users

**Comment by wakira** [comment]
Here is a screencast
![output](https://user-images.githubusercontent.com/2338339/218294434-bc4b740c-20cb-4c9a-ac13-0c745163add7.gif)
