### ISSUE TITLE
[Bug] Some pictures failed to drag

### ISSUE THREAD

**Issue by tiaramoe** [TwidereProject/TwidereX-Android#59]
# Bug Report

## Environment

Network type:

- [ ] Cellular
- [x] Wi-Fi

## Build Variant

- [x] Google Play
- [ ] FDroid

App version: 
1.1.0-beta02

### Steps to reproduce
https://twitter.com/ProjectPlateau/status/1379343586102104066?s=20
The second-third picture failed to drag.
### Actual Behavior
Cannot drag to the third picture
###  Expected behavior
Successfully switched to the next picture

**Comment by Tlaster** [comment]
Mark as fixed in the latest release
