### ISSUE TITLE
[Bug] Picture save failed

### ISSUE THREAD

**Issue by tiaramoe** [TwidereProject/TwidereX-Android#60]
# Bug Report

## Environment

Network type:

- [ ] Cellular
- [x] Wi-Fi

## Build Variant

- [x] Google Play
- [ ] FDroid

App version: 
1.1.0-beta02
## Bug Info
The picturesave feature isn't doing anything
### Steps to reproduce
Twitter/Mastodon - Click to enter the picture - Save at the bottom right corner - Save failed

###  Expected behavior

Successful save

**Comment by Tlaster** [comment]
Done in 1.1.0
