### ISSUE TITLE
[Bug] Scrolling through timelines on Twidere X is significantly choppier than on the old Twidere app

### ISSUE THREAD

**Issue by mbestavros** [TwidereProject/TwidereX-Android#63]
# Bug Report

## Environment

Network type:

- [ ] Cellular
- [x] Wi-Fi

## Build Variant

- [x] Google Play
- [ ] FDroid

App version: 

`1.1.0-beta02`

## Bug Info

Scrolling through any Twitter timeline -- the main feed, a user profile, etc. -- is significantly choppier, with more dropped frames, than on the old Twidere app.

This is occurring on a Pixel 4a (5G), which uses a Snapdragon 765G SoC -- not a flagship, but certainly powerful and more so than many mid-low-range Android devices.

### Steps to reproduce

Open Twidere X and scroll through a timeline with GPU profiling enabled.

### Actual Behavior

Routine frame skips when scrolling -- anecdotally, latency spikes seem to happen whenever a new post becomes visible.

Here is an example of a GPU profile on the new Twidere X app:

![Screenshot_20210411-214342](https://user-images.githubusercontent.com/10786787/114331040-21dfda80-9b11-11eb-8e13-babaed5b5393.png)

Documentation on how to read this profile is included [here](https://developer.android.com/topic/performance/rendering/inspect-gpu-rendering). Of note: 

> The horizontal green line represents 16 milliseconds. To achieve 60 frames per second, the vertical bar for each frame needs to stay below this line. Any time a bar surpasses this line, there may be pauses in the animations.

and 

> The tool highlights frames that exceed the 16 millisecond threshold by making the corresponding bar wider and less transparent.

As the above screenshot demonstrates, dropped frames (bars that surpass the horizontal green bar) are routine, seemingly due to frame time spikes that occur whenever a new post arrives in the viewport. This makes scrolling feel rather choppy and unpleasant.

###  Expected behavior

Scrolling through a timeline should almost never drop below 60 frames per second, and GPU profiles should reflect this.

Here is another GPU profile scrolling through the same user account (@TwidereProject) on the old Twidere app:

![Screenshot_20210411-214446](https://user-images.githubusercontent.com/10786787/114331445-fc9f9c00-9b11-11eb-9493-0b3634ffd9e0.png)

As can be seen in the screenshot's GPU profile, scrolling through this user account is completely smooth, almost never dropping below 60 fps. This is ideal, and what Twidere X should aspire to match.

**Comment by Tlaster** [comment]
This is a known issue for any Jetpack Compose application, `LazyColumn` performance is not as good as `RecyclerView`, just a simple text column on an old device (like my old Nexus 6P) will have horrible performance:
<img src="https://user-images.githubusercontent.com/8370277/114332636-2a6bfb80-9b79-11eb-9a7b-26b4966d2b8e.jpg" width="100" alt="68333650ly1gnymvrcbm9j22bc334x6q"/>
We're still waiting for the Google Compose team to optimize the performance of `LazyColumn`. Or we will rewrite the `LazyColumn` for ourselves.

**Comment by mbestavros** [comment]
Understood, glad y'all are aware! It really bothered me once I noticed it, and figured I'd write up a report. Hopefully it gets resolved soon -- I like lots of things the new app does. (Twitter list support soon please? 😄)

**Comment by nikclayton** [comment]
Untested, but https://www.reddit.com/r/androiddev/comments/n61qxh/jetpack_compose_lazycolumn_laggy/ suggests that using a different proguard config might help.

**Comment by Tlaster** [comment]
> Untested, but https://www.reddit.com/r/androiddev/comments/n61qxh/jetpack_compose_lazycolumn_laggy/ suggests that using a different proguard config might help.

R8 is enabled in version 1.5.1-beta01, it does perform better, but still not as good as old RecyclerView.

**Comment by mbestavros** [comment]
> > Untested, but https://www.reddit.com/r/androiddev/comments/n61qxh/jetpack_compose_lazycolumn_laggy/ suggests that using a different proguard config might help.
> 
> R8 is enabled in version 1.5.1-beta01, it does perform better, but still not as good as old RecyclerView.

@Tlaster One of the comments in the aforementioned link suggests that changing the default Proguard file to `proguard-android.txt` instead of `proguard-android-optimize.txt` in `build.gradle.kts` could have a significant impact.

Currently, TwidereX's config uses `proguard-android-optimize.txt` for the `release` build type, as seen [here](https://github.com/TwidereProject/TwidereX-Android/blob/develop/app/build.gradle.kts#L119). Perhaps it's worth a try to change it to `proguard-android.txt`?

**Comment by Tlaster** [comment]
> > > Untested, but https://www.reddit.com/r/androiddev/comments/n61qxh/jetpack_compose_lazycolumn_laggy/ suggests that using a different proguard config might help.
> > 
> > 
> > R8 is enabled in version 1.5.1-beta01, it does perform better, but still not as good as old RecyclerView.
> 
> @Tlaster One of the [comments](https://www.reddit.com/r/androiddev/comments/n61qxh/jetpack_compose_lazycolumn_laggy/h8b9c8m/?utm_source=reddit&utm_medium=web2x&context=3) in the aforementioned link suggests that changing the default Proguard file to `proguard-android.txt` instead of `proguard-android-optimize.txt` in `build.gradle.kts` could have a significant impact.
> 
> Currently, TwidereX's config uses `proguard-android-optimize.txt` for the `release` build type, as seen [here](https://github.com/TwidereProject/TwidereX-Android/blob/develop/app/build.gradle.kts#L119). Perhaps it's worth a try to change it to `proguard-android.txt`?

Thanks, I'll have a try.

**Comment by Fs00** [comment]
Hello guys, I just wanted to chime in to make sure this issue doesn't get underrated.
It is not just a matter of the scrolling being choppier: it makes the app completely unusable on older phones.
For example, this is a screenshot of the GPU profiling when scrolling up/down through the timeline on my Xperia X Compact (Snapdragon 650):

![Screenshot_20210903-190603](https://user-images.githubusercontent.com/30041551/132043541-83f128b9-fde2-4b87-a812-56a27a9a09ca.png)

I hope the situation will improve someday :disappointed:
