### ISSUE TITLE
[Bug] Highlight "selection" effect while scrolling

### ISSUE THREAD

**Issue by katerkalu** [TwidereProject/TwidereX-Android#64]
# Bug Report

## Environment

Network type:

- [x ] Cellular
- [x ] Wi-Fi

## Build Variant

- [x ] Google Play
- [x ] FDroid

App version: 
1.0.6

### Steps to reproduce

scroll with the app

### Actual Behavior

when you scroll, a selection effect will come up wherever you touch the screen

###  Expected behavior

scrolling without any effects on screen

**Comment by Tlaster** [comment]
duplicate #33
