### ISSUE TITLE
[Bug] RTL Problem

### ISSUE THREAD

**Issue by neptu39701** [TwidereProject/TwidereX-Android#67]
# Bug Report

## Environment

Network type:

- [x] Cellular
- [x] Wi-Fi

## Build Variant

- [ ] Google Play
- [x] FDroid

App version: 
1.0.6
## Bug Info

Text Direction Problem in RTL Texts

### Steps to reproduce

All Texts Are LTR by default if you write something in RTL language its gonna start from left

### Actual Behavior

Texts Are LTR by default
  
###  Expected behavior

RTL languages Texts should be directed RTL

**Comment by Tlaster** [comment]
After talking to Google Android Text Team, this behavior is on purpose.

> however after talking with i18n experts a bunch we decided that the current state is the best but actually none of the defaults are best

So it's quite difficult to decide which is the best. We just follow Google's default behavior for now.
