### ISSUE TITLE
[Bug] With Pleroma account setup, Mentions tab is empty

### ISSUE THREAD

**Issue by AMoonRabbit** [TwidereProject/TwidereX-Android#75]
I have linked my Pleroma account to Twidere X, and for the most part, things appear to be okay. However, whilst I can see notifications, if I switch the view to just mentions, the view remains empty.

![Screenshot_20210424-182546](https://user-images.githubusercontent.com/3766988/115967653-ba238980-a52b-11eb-82e1-5d895562dbaa.png)

**Steps to reproduce:**
1. Log into Twidere X with a pleroma account
2. Wait for the account to sync and check timeline and notifications
3. Switch notification view from All to Mentions

**Expected behaviour**
Mentions tab should show a filtered notifications stream that only includes toots that mention you, stripping boosts and favourites from the view.

**Version**
1.1.0 beta 3
Android 11
Pixel 4

**Comment by Tlaster** [comment]
Can not reproduce the issue, can you provide which instance you're using?

**Comment by Tlaster** [comment]
Close the issue, reopen if you're still encountering the same issue.
