### ISSUE TITLE
[Bug] Interactions and Mentions stop updating

### ISSUE THREAD

**Issue by AMoonRabbit** [TwidereProject/TwidereX-Android#78]
# Bug Report

## Environment

Network type:

- [X] Cellular
- [X] Wi-Fi

## Build Variant

- [X] Google Play
- [ ] FDroid

App version: 
v1.1.0-beta4

### Steps to reproduce

1. Configure Pleroma account in app
2. Use for a few days
3. Check notifications and compare with web UI or other apps

### Actual Behavior

Notification tab stops updating for Pleroma instance. Compared to my instance and other apps, TwidereX is now 3 days behind on notifications and pull to refresh does not force an update. The main stream however, and ability to toot still works.

###  Expected behavior

Notification channel should have all interactions and mentions up to date.

**Comment by Tlaster** [comment]
Mark as duplicated with #75
