### ISSUE TITLE
[Bug] videos show preview in opened video

### ISSUE THREAD

**Issue by stop5** [TwidereProject/TwidereX-Android#81]
# Bug Report

## Environment

Network type:

- [ ] Cellular
- [X] Wi-Fi

## Build Variant

- [X] Google Play
- [ ] FDroid

App version: 
1.1.0

### Steps to reproduce:

click on a video/GIf fromthe timeline to view it.

### Actual Behavior

theVideo/GIF is played, but the small image/video is also displayed over it.

###  Expected behavior

just the video/image.
![IMG_20210428_115131.jpg](https://user-images.githubusercontent.com/6901125/116384545-3eba2480-a818-11eb-8cb6-17b0b652b826.jpg)

**Comment by stop5** [comment]
It could be a bit hard to reproduce. When i switched apps and the video was visible in the timeline or opened the bug disappeared.

**Comment by tiaramoe** [comment]
This also happens in Samsung Galaxy Note 10+ With android 11
