### ISSUE TITLE
Attempting to like tweets results in CtH

### ISSUE THREAD

**Issue by AMoonRabbit** [TwidereProject/TwidereX-Android#9]
As of this morning on 1.0.0-alpha5, attempting to like any tweet results in the app crashing to homescreen. I have submitted the error report via Google play.

**Comment by Kreuger** [comment]
Mine doesnt crash but it wont like the post either.

**Comment by Tlaster** [comment]
This should be fixed after 1.0.0-alpha07, reopen if you're still encountering this issue

**Comment by Kreuger** [comment]
Im now having this issue on the new alpha. Please reopen.

**Comment by Tlaster** [comment]
oops! seems like there's another bug!

**Comment by Kreuger** [comment]
Today when attempting to like tweets with the alpha08, it keeps telling me there are too mqny requests.

**Comment by Tlaster** [comment]
It seems like a limitation from Twitter that prevent malicious use, I'm encountering the same issue but after switching the network (from wifi to data for example), it works as normal.

**Comment by Kreuger** [comment]
Interesting. I didnt notice when it started working again. I will keep that in mind.

**Comment by winterhazelly** [comment]
for what it's worth, I'm also having this issue ("too many requests") and just tried switching from wifi to data and it didn't help. retweets work.

**Comment by Tlaster** [comment]
It seems no longer an issue anymore, closing it.
Reopen if you still encountering the same issue.
