### ISSUE TITLE
Twitter Polls are Missing

### ISSUE THREAD

**Issue by trev-dev** [TwidereProject/TwidereX-Android#93]
# Bug Report
Twitter polls are missing entirely. 

## Environment

Network type:

- [ ] Cellular
- [x] Wi-Fi

## Build Variant

- [x] Google Play
- [ ] FDroid

App version: 
1.1.0

## Bug Info
I get the sense that Twitter may not provide poll data via the API, but if it is possible to at least know that a poll exists somehow so that I may check the web version of the post, that would be a reasonable workaround 

### Steps to reproduce
Find a Tweet with a poll. Look at it on Twidere X

### Actual Behavior
Polls are missing, tweets missing context for polls become confusing.

###  Expected behavior
Ideally, a fully working poll feature where you may create and consume polls. If possible, at least be able to know a poll is supposed to be there.

**Comment by Tlaster** [comment]
Twitter's new v2 API does come with poll information, but currently not all API is in v2, the home timeline for example, and there is no API to create and consume poll. We're still waiting for Twitter to fully release of v2 API.

**Comment by trev-dev** [comment]
Thanks @Tlaster. This isn't a bug, then. It's an API limitation for now. I'm sure polls are on a priority list somewhere. Closing this

**Comment by mimi89999** [comment]
Do you know if there was any progress on this?

**Comment by yoshimo** [comment]
https://developer.twitter.com/en/docs/twitter-api/data-dictionary/object-model/poll
Should be possible now
